database:
   driverClass: com.mysql.jdbc.Driver	
   user: root	  
   password: root    	   
   url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC   
   properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MySQLDialect  
      hibernate.show_sql: true
      
   